### PR TITLE
More complete descriptions for modelling libraries

### PR DESCRIPTION
**Pull request by dourouc05**
Give descriptions for those in Python. For each, say whether it's CP and/or MILP. I decided to leave out MINLP, mostly to avoid having too long entries (and because it can be a totally different set of tools, maybe it's worth having an MINLP modelling section later on).

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!

btw do you think we should also add SMT solvers like z3 or heuristic based libraries (Genetic Algorithms, etc)?

**Comment by dourouc05** [comment]
I would say so, because they can be very useful (but SMT in fewer situations, I would say).

By the way, do you think it would be better to change the part about solvers into a table? Rows would be solvers and columns the type of problem they can solve (with a tick each time the combination is supported). Another option is to have a column with a list of problem types that are supported (like https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers).

**Comment by ghost** [comment]
Sounds great, I wouldn't want to add too many columns so maybe something like the legend that JuMP uses works?

**Comment by Mizux** [comment]
My 2 cents,
some ref:
https://en.wikipedia.org/wiki/Linear_programming#Solvers_and_scripting_(programming)_languages
https://en.wikipedia.org/wiki/Satisfiability_modulo_theories#Solvers

**Pull request merged**
